# Define the stack configuration form and organize inputs of various types into sections and groups.
# See: https://docs.staging.cycloid.io/deploy/stackforms/file-format.html
use_cases:
- name: aws
  sections:
  - name: Cloud provider
    groups:
    - name: Access
      technologies: [pipeline]
      vars:
      - name: "Aws region"
        key: aws_default_region
        type: string
        widget: auto_complete
        values: ["eu-north-1", "ap-south-1", "eu-west-3", "eu-west-2", "eu-west-1", "ap-northeast-2", "ap-northeast-1", "sa-east-1", "ca-central-1", "ap-southeast-1", "ap-southeast-2", "eu-central-1", "us-east-1", "us-east-2", "us-west-1", "us-west-2"]
        default: "eu-west-1"
      - name: "AWS access key"
        description: "AWS access key which should be used"
        key: aws_cred
        type: string
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types: [aws]
        default: "((aws))"

  - name: Terraform variable example
    groups:
    - name: Configuration
      technologies: [terraform]
      vars:
      - name: "Tshirt size"
        description: "This is a **Terraform variable example**"
        key: module.example.tshirt_size # Module name should match the Terraform module name specified in main.tf.sample
        type: string
        widget: auto_complete
        values: ["S", "M", "L", "XXL"]
        default: "M"
