#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#

module "example" {
  source = "./module-sample"

  component    = var.component
  env          = var.env
  organization = var.organization
  project      = var.project
  tshirt_size  = "M"
}

