version: '4'
name: gael-v4-terraform-gcp
canonical: gael-v4-terraform-gcp
author: 'admin'
# Fill in the stack details.
description: 'Discover how to integrate Terraform in your pipelines.'
image: https://github.com/cycloidio/bootstrap-stacks/blob/master/blank-sample/thumbnail.png
keywords:
  - 'terraform'
  - 'gcp'
technologies:
  - technology: terraform
    version: 1.8.2
template: false
status: 'public'
# Add use cases to the stack.
# See: https://docs.cycloid.io/manage/pipeline/multi-use-case.html#multiple-use-case
config:
  gcp:
    name: 'GCP'
    description: 'Manage Google Cloud Platform (google) resources.'
    cloud_provider: google
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/main.tf.sample'
        destination: '($ .organization_canonical $)/($ .project $)/($ .environment $)/($ .component $)/terraform/main.tf'
