version: "2"
name: imported
canonical: imported
author: admin
description: imported
image: ""
keywords:
- keyword
- provider:aws
template: false
template_ignore: []
technologies: []
dependencies: []
config:
  default:
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      imported:
        destination: ($ project $)/terraform/($ environment $)/imported.tf
        path: terraform/default/imported.tf.sample
