version: "2"
name: Stack imported
canonical: stack_imported
author: admin
description: imported and testing
image: ""
keywords:
- imported
- provider:aws
- provider:gcp
template: false
template_ignore: []
technologies: []
dependencies: []
config:
  default:
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      stack_imported:
        destination: ($ project $)/terraform/($ environment $)/stack_imported.tf
        path: terraform/default/stack_imported.tf.sample
