version: "2"
name: test visib 2
canonical: test_visib_2
author: admin
description: The bare minimum files to build your stack from scratch. 1
image: https://github.com/cycloidio/bootstrap-stacks/blob/master/blank-sample/thumbnail.png
keywords: []
template: false
template_ignore: []
technologies: []
dependencies: []
config:
  default:
    name: Default
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        destination: ($ .project $)/pipeline/variables-($ .environment $).yml
        path: pipeline/variables.samples.yml
