version: "2"
name: array and maps validations
canonical: array_and_maps_validations
author: Javier
description: The bare minimum files to build your stack from scratch.
image: https://github.com/cycloidio/bootstrap-stacks/blob/master/blank-sample/thumbnail.png
keywords: []
template: false
template_ignore: []
technologies: []
dependencies: []
config:
  validation:
    name: Validations
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/variables.sample.yml
