version: "4"
name: array and maps validations test
canonical: array_and_maps_validations
author: admin
description: The bare minimum files to build your stack from scratch.
image: https://github.com/cycloidio/bootstrap-stacks/blob/master/blank-sample/thumbnail.png
keywords: []
template: false
template_ignore: []
technologies: []
dependencies: []
config:
  validation:
    name: Validations
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        destination: ($ .organization_canonical $)/($ .project $)/($ .environment $).yml
        path: pipeline/variables.sample.yml
