version: 2

use_cases:
- name: validation
  sections:
  - name: Example section
    groups:
    - name: Example group
      technologies: [pipeline]
      vars:

      # ARRAY VALIDATION
      #   - name: "Image MIME types"
      #     key: image-mime-types
      #     widget: text_area
      #     type: array
      #     default:
      #       - "image/jpeg"
      #       - "image/png"
      #       - "image/gif"
      #       - "image/webp"
      #     validations:
      #       - error_message: "The image/jpeg MIME type is required."
      #         array:
      #           must_exist_elems: ["image/jpeg"]
      #       - error_message: "The image/png MIME type is required."
      #         array:
      #           must_exist_elems: ["image/png"]
      #       - error_message: "You must provide at least two MIME types."
      #         array:
      #           min_elems: 2
      #       - error_message: "You must not provide more than five MIME types."
      #         array:
      #           max_elems: 5

      # # MAP VALIDATIONS
      #   - name: "Load test parameters"
      #     key: load-test-params
      #     widget: text_area
      #     type: map
      #     default:
      #       users: 100
      #       duration: 10m
      #       endpoint: "/api"
      #     validations:
      #       - map:
      #           must_exist_keys: ["endpoint"]
      #         error_message: 'endpoint must be present'
      #       - map:
      #           must_exist_keys: ["users"]
      #         error_message: 'users must be present'

        - widget: "dropdown"
          values: [[ "lb2",32223], [ "lb1", 32223], [ "lb3", 52224, 'test']]
          type: "array"
          description: "something k2"
          key: "key-test-no-validation"
          name: "array variable"
          widget_config:
              multiselect: true

        - widget: "dropdown"
          values: [[ "lb2",32223], [ "lb1", 32223], [ "lb3", 52224, 'test']]
          type: "array"
          description: "something k2"
          key: "key-test"
          name: "array variable"
          widget_config:
              multiselect: true
          validations:
            - array:
                must_exist_elems: [["lb1", 32223]]
              error_message: 'lb1 must be present'
            - array:
                max_elems: 2

        # - widget: "dropdown"
        #   type: "array"
        #   values: [{T: foo, value: t3}, {T: foo1}, {value: t4}]
        #   default: [{T: foo, value: t3}]
        #   description: "object values"
        #   key: "key-one"
        #   name: "map variable"
        #   widget_config:
        #     multiselect: true
        #   validations:
        #     - map:
        #         must_exist_keys: ["T"]
        #       error_message: 'T key must be present'