#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#

module "vm" {
  source = "./module-ec2"

  ami_architecture = "x86_64"
  ami_most_recent  = true
  ami_name         = "debian-12-amd64-*"
  ami_owners = [
    "379101102735",
    "136693071363",
    "125523088429",
    "099720109477",
    "309956199498"
  ]
  ami_root_device_type                 = "ebs"
  ami_virtualisation_type              = "hvm"
  associate_public_ip_address          = true
  customer                             = var.customer
  ebs_optimized                        = false
  enable_vm_disk_delete_on_termination = true
  enable_vm_disk_encrypted             = true
  env                                  = var.env
  file_content                         = ""
  instance_extra_tags = {
  }
  instance_type = "t3.micro"
  key_name      = ""
  private_ip    = ""
  project       = var.project
  sg_egress_rules = [
    {
      cidr_blocks = [
        "0.0.0.0/0"
      ]
      description = "Accept all egress"
      from_port   = 0
      ipv6_cidr_blocks = [

      ]
      prefix_list_ids = [

      ]
      protocol = "-1"
      security_groups = [

      ]
      self    = true
      to_port = 0
    }
  ]
  sg_extra_tags = {
  }
  sg_ingress_rules = [
    {
      cidr_blocks = [
        "0.0.0.0/0"
      ]
      description = "Accept ssh traffic"
      from_port   = 22
      ipv6_cidr_blocks = [

      ]
      prefix_list_ids = [

      ]
      protocol = "tcp"
      security_groups = [

      ]
      self    = true
      to_port = 22
    }
  ]
  sg_name      = ""
  subnet_id    = "test"
  vm_disk_size = 20
  vm_disk_type = "gp2"
  volume_extra_tags = {
  }
  vpc_id = "test"
}

